Repository googleapis/nodejs-service-management, pull requests merged in 2021-05, with the labels that each got.

#47 build: update falsy values in protos.d.ts
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: api: servicemanagement, cla: yes, context: none

#48 fix(deps): require google-gax v2.12.0
  package.json
Labels: api: servicemanagement, automerge, cla: yes

#50 fix: use require() to load JSON protos
  src/v1/service_manager_client.ts
  synth.metadata
Labels: api: servicemanagement, cla: yes, context: full

#52 build: remove codecov action, update linting
  .github/workflows/ci.yaml
  src/v1/service_manager_client.ts
  synth.metadata
  test/gapic_service_manager_v1.ts
Labels: api: servicemanagement, automerge, cla: yes, context: partial

#39 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .github/generated-files-bot.yml
  .repo-metadata.json
  synth.py
Labels: api: servicemanagement, cla: yes
