Repository googleapis/nodejs-service-management, pull requests merged in 2021-04, with the labels that each got.

#29 build: fix blank distribution name
  .repo-metadata.json
Labels: api: servicemanagement, cla: yes

#43 build: update links and package name
  .jsdoc.js
  README.md
  linkinator.config.json
  protos/google/api/servicemanagement/v1/resources.proto
  protos/google/api/servicemanagement/v1/servicemanager.proto
  src/v1/gapic_metadata.json
  src/v1/service_manager_client.ts
  synth.metadata
Labels: api: servicemanagement, cla: yes, context: partial

#44 build(node): remove unused tokens
  .github/workflows/ci.yaml
  .kokoro/release/publish.cfg
  synth.metadata
Labels: api: servicemanagement, cla: yes, context: full

#45 build: add generated-files bot config
  .github/generated-files-bot.yml
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: servicemanagement, automerge, cla: yes, context: full
